language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
before_script:

script:
  - python manage.py test

notifications:
  irc:
    channels:
      - "chat.freenode.net#healthdb"
    template:
      - " %{author} %{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"